"""Models package."""

from app.models.email.schemas import (
    ClassifiedEmail,
    DecidedBy,
    EmailAttachment,
    EmailCategory,
    ParsedEmail,
)
from app.models.extraction import (
    ALL_COMPARISON_FIELDS,
    BoundingBox,
    ComparisonField,
    DocumentFieldCandidates,
    DocumentRole,
    EvidenceReference,
    ExtractionMethod,
    FieldCandidate,
    PageRegionLocator,
    TableCellLocator,
    TextSpanLocator,
)
from app.models.health import HealthResponse
from app.models.verification import (
    CandidateAssessment,
    DocumentNormalizationResult,
    DocumentVerificationResult,
    FieldVerificationResult,
    NormalizationFailure,
    NormalizationIssue,
    NormalizationRule,
    NormalizationStep,
    NormalizedDocument,
    NormalizedField,
    NormalizedIntegerValue,
    NormalizedTextValue,
    NormalizedWeightKgValue,
    VerificationIssue,
    VerificationOutcome,
    VerifiedField,
    VerifiedNormalizedPair,
)

__all__ = [
    "ALL_COMPARISON_FIELDS",
    "BoundingBox",
    "CandidateAssessment",
    "ClassifiedEmail",
    "ComparisonField",
    "DocumentFieldCandidates",
    "DocumentRole",
    "DocumentNormalizationResult",
    "DocumentVerificationResult",
    "DecidedBy",
    "EmailAttachment",
    "EmailCategory",
    "EvidenceReference",
    "ExtractionMethod",
    "FieldVerificationResult",
    "FieldCandidate",
    "HealthResponse",
    "NormalizationRule",
    "NormalizationFailure",
    "NormalizationIssue",
    "NormalizationStep",
    "NormalizedDocument",
    "NormalizedField",
    "NormalizedIntegerValue",
    "NormalizedTextValue",
    "NormalizedWeightKgValue",
    "PageRegionLocator",
    "ParsedEmail",
    "TableCellLocator",
    "TextSpanLocator",
    "VerificationIssue",
    "VerificationOutcome",
    "VerifiedField",
    "VerifiedNormalizedPair",
]
